# Generated by Django 5.2.1 on 2025-05-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='nama',
            new_name='name',
        ),
    ]
